spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    username: JVA_MS
    password: JVA_MS
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ORCLPDB1.localdomain)))